### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by flippedcracker** [SiwatINC/home_assistant_control_panel_unraid#1]
When trying to run container, get an error message that the certificate for https://reformedreality.com/hass-download has expired.

> removed '/var/www/html/index.nginx-debian.html'
--2019-06-21 22:33:48-- https://reformedreality.com/hass-download
Resolving reformedreality.com (reformedreality.com)... 52.16.150.64, 2001:8d8:100f:f000::200
Connecting to reformedreality.com (reformedreality.com)|52.16.150.64|:443... connected.
ERROR: cannot verify reformedreality.com's certificate, issued by 'CN=Starfield Secure Certificate Authority - G2,OU=http://certs.starfieldtech.com/repository/,O=Starfield Technologies\\, Inc.,L=Scottsdale,ST=Arizona,C=US':
Issued certificate has expired.
To connect to reformedreality.com insecurely, use `--no-check-certificate'.

**Comment by SiwatS** [comment]
Temporary added --no-check-certificate until the certificate is renewed

**Comment by flippedcracker** [comment]
I don't think the dockerhub file updated. Still getting the same error when trying to start the container.

**Comment by flippedcracker** [comment]
Working now. Thanks.
